author = "Tom Maiaroto"
description = "A clean, responsive, template with red accents."
license = "MIT"
name = "redlounge"
source_repo = ""
tags = ["redlounge", "red", "raleway", "libre baskerville", "blog"]
